language: node_js

node_js:
  - '10.15.3'

notifications:
  email:
    on_success: change # only if status change from fail to success
    on_failure: always # if there is a fail
    recipients:
      - a.diasbarreto@icloud.com
      - albericodiasbarretofilho@gmail.com

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - bash ./deploy.sh
